#Configured by Chyngyz Sharshekeev at 2pm 25.07.2022

name: TaskTracker-CICD-Pipeline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME: ""
  EB_APPLICATION_NAME      : "taskTracker"
  EB_ENVIRONMENT_NAME      : "Tasktracker-env"
  DEPLOY_PACKAGE_NAME      : "taskTracker_${{ github.sha }}.zip"
  AWS_REGION_NAME          : "eu-central-1"

on:
  push:
    branches:
      - main

jobs:
  ci_part:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repo
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: target/taskTracker.jar

  cd_part:
    runs-on: ubuntu-latest
    needs  : [ci_part]

    steps:
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: artifact

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          use_existing_version_if_available: true
          application_name: ${{ env.EB_APPLICATION_NAME }}
          environment_name: ${{ env.EB_ENVIRONMENT_NAME  }}
          version_label: ${{ github.SHA }}
          region: ${{ env.AWS_REGION_NAME }}
          deployment_package: taskTracker.jar